/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-17 10:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"./resources/js/board.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Blog Hero Begin -->\r\n");
      out.write("    <section class=\"breadcrumb-option blog-hero set-bg\" data-setbg=\"./resources/img/breadcrumb.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"blog__hero__text\">\r\n");
      out.write("                        <h2>자유 게시판</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Hero End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Blog Details Section Begin -->\r\n");
      out.write("    <section class=\"blog-details spad\">\r\n");
      out.write("    \t\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"row\" style=\"justify-content: center\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-8 order-lg-2 order-1\">\r\n");
      out.write("                \t<div style=\"margin-bottom: 30px;text-align: center;\">\r\n");
      out.write("                \t\t<span style=\"font-size: 1.3em; font-weight: bold;\">100일만에 -10kg만든 운동법</span>\r\n");
      out.write("                \t</div>\r\n");
      out.write("                \t<div  style=\"text-align: right;margin-bottom: 5px;padding-right: 8px;\">\r\n");
      out.write("                        <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                        \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"display: inline-block;\">\r\n");
      out.write("                        \t<p>1000</p>\r\n");
      out.write("                        </div> |&nbsp;\r\n");
      out.write("                        <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                        \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"display: inline-block;\">\r\n");
      out.write("                        \t<p>2000</p>\r\n");
      out.write("                        </div> |&nbsp;\r\n");
      out.write("                        <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                        \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"display: inline-block;\">\r\n");
      out.write("                        \t<p>400</p>\r\n");
      out.write("                        </div>&nbsp;\r\n");
      out.write("                        <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                        \t<img src=\"./resources/img/common/bookmark_.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("                        </div> \r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("                    <div class=\"blog__details\">\r\n");
      out.write("                    \t<div style=\"border:1px solid; width: auto;height: 800px;\" >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<p>여기에 작성글이 들어옵니다</p>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"text-align: center;\">\r\n");
      out.write("                            <a href=\"boardList\" class=\"class-btn\">목록</a>\r\n");
      out.write("\t                        <a href=\"boardMod\" class=\"class-btn\">수정</a>\r\n");
      out.write("\t                        <a href=\"#\" class=\"class-btn\">삭제</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Details Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Leave Comment Begin -->\r\n");
      out.write("    <div class=\"leave-comment spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"leave__comment__text\">\r\n");
      out.write("                        <h2>자유롭게 댓글을 달아보세요😁</h2>\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-12\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                                    <textarea placeholder=\"댓글을 입력해 주세요.\"></textarea>\r\n");
      out.write("                                    <button type=\"submit\" class=\"site-btn\" style=\"font-size: 1.2em;\">작성 완료</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-4 order-lg-1 order-2\" style=\"width: 100%;flex: 0 0 100%;max-width: 100%;padding-right: 0px;margin-left: 23px;\">\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"blog__sidebar\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"blog__sidebar__comment\" style=\"overflow:scroll; height: 500px;\">\r\n");
      out.write("                            <h4>댓글</h4>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-2.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Christina Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Leave Comment End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"./resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
