/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-17 10:12:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Breadcrumb Begin -->\r\n");
      out.write("    <section class=\"breadcrumb-option set-bg\" data-setbg=\"./resources/img/breadcrumb.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb__text\">\r\n");
      out.write("                        <h2>자유 게시판</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Breadcrumb End -->\r\n");
      out.write("\t <!-- Team Section Begin -->\r\n");
      out.write("    <section class=\"team spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <h3>인기 게시판글 TOP 3</h3>\r\n");
      out.write("                        <p>지금 가장 인기있는 게시판글을 확인해 보세요!!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"team__slider owl-carousel\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"team__item\" style=\"padding-top:10px;padding-bottom: 10px;\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes-details/cd-item-3.jpg\">\r\n");
      out.write("                            <span>20 Jun 2020</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-top: 10px;padding-bottom: 10px; padding-left: 0;padding-right: 0;\">\r\n");
      out.write("                            <div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"#\">명상을 합시다 여러부운운운!!</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">뽀미언니</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"team__item\" style=\"padding-top:10px;padding-bottom: 10px;\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/deit_2.jpg\">\r\n");
      out.write("                            <span>20 Jun 2020</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-top: 10px;padding-bottom: 10px; padding-left: 0;padding-right: 0;\">\r\n");
      out.write("                            <div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"#\">가볍고 든든한 다이어트 한끼 식사</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">뽀미언니</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"team__item\" style=\"padding-top:10px;padding-bottom: 10px;\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/deit_2.jpg\">\r\n");
      out.write("                            <span>20 Jun 2020</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-top: 10px;padding-bottom: 10px; padding-left: 0;padding-right: 0;\">\r\n");
      out.write("                            <div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"#\">가볍고 든든한 다이어트 한끼 식사</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">뽀미언니</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Team Section End -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <!-- Classes Section Begin -->\r\n");
      out.write("    <section class=\"classes spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"classes__filter\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"class__filter__select\">\r\n");
      out.write("                                <p>Categories:</p>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>카테고리</option>\r\n");
      out.write("                                    <option>운동</option>\r\n");
      out.write("                                    <option>식단</option>\r\n");
      out.write("                                    <option>동기부여</option>\r\n");
      out.write("                                    <option>생활습관</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__select\">\r\n");
      out.write("                                <p>Level:</p>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>전체</option>\r\n");
      out.write("                                    <option>조회순</option>\r\n");
      out.write("                                    <option>좋아요순</option>\r\n");
      out.write("                                    <option>댓글순</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__input\">\r\n");
      out.write("                                <p>Search:</p>\r\n");
      out.write("                                \t<input type=\"text\" placeholder=\"검색\" >\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__btn\">\r\n");
      out.write("                                <button><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"classes__item__text\" style=\"text-align: right;padding-top: 0;\">\r\n");
      out.write("                 <span class=\"blinking\">당신의 특별한 Tip을 공유해보세요 → </span>&nbsp;\r\n");
      out.write("                 <a href=\"boardAdd\" class=\"class-btn_w\">글쓰기</a>\r\n");
      out.write("   \t\t \t</div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\" style=\"padding-left: 5px;padding-right: 5px;\">\r\n");
      out.write("                        \t\r\n");
      out.write("                        \t<div style=\"text-align: right;\">\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/look.PNG\" style=\"width:30px;height: 20px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>1000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/reply.PNG\" style=\"width:24px;height: 19px;opacity: 0.5;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>2000</p>\r\n");
      out.write("\t                            </div> |&nbsp;\r\n");
      out.write("\t                            <div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("\t                            \t<img src=\"./resources/img/common/good.PNG\" style=\"width:22px;height: 20px;\">\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                            <div style=\"display: inline-block;\">\r\n");
      out.write("\t                            \t<p>400</p>\r\n");
      out.write("\t                            </div> \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>카테고리 | 운동</p>\r\n");
      out.write("                            <h4 style=\"margin-bottom: 30px;\"><a href=\"boardDetail\">100일만에 -10kg만든 운동법</a></h4>\r\n");
      out.write("                            <div>\r\n");
      out.write("                            \t<div style=\"display: inline-block;vertical-align: middle;\">\r\n");
      out.write("                            \t\t<img src=\"./resources/img/common/writer.PNG\" style=\"width:24px;height: 26px;opacity: 0.5;\" />\r\n");
      out.write("                            \t</div>&nbsp;\r\n");
      out.write("                            \t<div style=\"display: inline-block;\">\r\n");
      out.write("                            \t\t<h6 style=\"margin-bottom: 25px;\">동그리동동</h6>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"boardDetail\" class=\"class-btn\" style=\"width:100%; text-align: center;\">상세보기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"classes__pagination\">\r\n");
      out.write("                        <a href=\"#\">1</a>\r\n");
      out.write("                        <a href=\"#\">2</a>\r\n");
      out.write("                        <a href=\"#\"><span class=\"arrow_carrot-right\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Classes Section End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"./resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
