/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-16 05:21:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Hero Section Begin -->\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("        <div class=\"hero__sliders owl-carousel\">\r\n");
      out.write("            <div class=\"hero__items set-bg\" data-setbg=\"./resources/img/hero/hero-1.jpg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <span>Welcome to Zogin</span>\r\n");
      out.write("                                <h2>What hurts today makes you stronger tomorrow</h2>\r\n");
      out.write("                                <a href=\"#\" class=\"primary-btn\">DISCOVER MORE</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hero__items set-bg\" data-setbg=\"./resources/img/hero/hero-1.jpg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-8\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <span>Welcome to Zogin</span>\r\n");
      out.write("                                <h2>What hurts today makes you stronger tomorrow</h2>\r\n");
      out.write("                                <a href=\"#\" class=\"primary-btn\">DISCOVER MORE</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Hero Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- About Section Begin -->\r\n");
      out.write("    <section class=\"home-about spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-7\">\r\n");
      out.write("                    <div class=\"home__about__pic\">\r\n");
      out.write("                        <div class=\"home__about__pic__item large-item set-bg\" data-setbg=\"./resources/img/about/about-1.jpg\"></div>\r\n");
      out.write("                        <div class=\"home__about__pic__item\">\r\n");
      out.write("                            <div class=\"home__about__pic__item__inner set-bg\" data-setbg=\"./resources/img/about/about-2.jpg\"></div>\r\n");
      out.write("                            <div class=\"home__about__pic__item__inner set-bg\" data-setbg=\"./resources/img/about/about-3.jpg\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-5\">\r\n");
      out.write("                    <div class=\"home__about__text\">\r\n");
      out.write("                        <div class=\"section-title\">\r\n");
      out.write("                            <img src=\"./resources/img/icon.png\" alt=\"\">\r\n");
      out.write("                            <h2>Welcome to Zogin</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <span>âWhat hurts today makes you stronger tomorrow.â</span>\r\n");
      out.write("                        <p>We are offering internationally certified 200 Hour Yoga Teacher Training in Rishikesh and 300\r\n");
      out.write("                            hour yoga teacher training in Rishikesh, India - Join us to have such life-transforming\r\n");
      out.write("                            experience in The world capital of Yoga in Rishikesh.</p>\r\n");
      out.write("                        <p class=\"para-2\">Zogin is a great place for those who are in search of the ancient practice and\r\n");
      out.write("                            true essence of yoga, meditation, health, peace and learning the art of creating a class to\r\n");
      out.write("                            teach safely. We are passionate about adjustments and mainly focus on the alignment of the\r\n");
      out.write("                            asanas.</p>\r\n");
      out.write("                        <a href=\"#\" class=\"primary-btn\">MORE ABOUT US</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- About Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Services Section Begin -->\r\n");
      out.write("    <section class=\"services spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <img src=\"./resources/img/icon.png\" alt=\"\">\r\n");
      out.write("                        <h2>Enjoy All Aspects Of Yoga</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"services__list\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"services__item\">\r\n");
      out.write("                            <img src=\"./resources/img/services/services-1.png\" alt=\"\">\r\n");
      out.write("                            <h5>Asana</h5>\r\n");
      out.write("                            <p>Grab the opportunity to deepen your own yoga practice, relax, restore and experience\r\n");
      out.write("                                india!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"services__item\">\r\n");
      out.write("                            <img src=\"./resources/img/services/services-2.png\" alt=\"\">\r\n");
      out.write("                            <h5>Meditation</h5>\r\n");
      out.write("                            <p>Grab the opportunity to deepen your own yoga practice, relax, restore and experience\r\n");
      out.write("                                india!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"services__item\">\r\n");
      out.write("                            <img src=\"./resources/img/services/services-3.png\" alt=\"\">\r\n");
      out.write("                            <h5>Mudra</h5>\r\n");
      out.write("                            <p>Grab the opportunity to deepen your own yoga practice, relax, restore and experience\r\n");
      out.write("                                india!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"services__item\">\r\n");
      out.write("                            <img src=\"./resources/img/services/services-4.png\" alt=\"\">\r\n");
      out.write("                            <h5>Bandhas</h5>\r\n");
      out.write("                            <p>Grab the opportunity to deepen your own yoga practice, relax, restore and experience\r\n");
      out.write("                                india!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"services__item\">\r\n");
      out.write("                            <img src=\"./resources/img/services/services-5.png\" alt=\"\">\r\n");
      out.write("                            <h5>Philosophy</h5>\r\n");
      out.write("                            <p>Grab the opportunity to deepen your own yoga practice, relax, restore and experience\r\n");
      out.write("                                india!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-2 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"services__item\">\r\n");
      out.write("                            <img src=\"./resources/img/services/services-6.png\" alt=\"\">\r\n");
      out.write("                            <h5>Pranayama</h5>\r\n");
      out.write("                            <p>Grab the opportunity to deepen your own yoga practice, relax, restore and experience\r\n");
      out.write("                                india!</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Services Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Chooseus Section Begin -->\r\n");
      out.write("    <section class=\"chooseus spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"chooseus__text\">\r\n");
      out.write("                        <h2>Why Choose Us</h2>\r\n");
      out.write("                        <p>We are offering internationally certified 200 Hour Yoga Teacher Training in Rishikesh and 300\r\n");
      out.write("                            hour yoga teacher training in Rishikesh, India - Join us to have such life-transforming\r\n");
      out.write("                            experience in The world capital of Yoga in Rishikesh.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chooseus__item\">\r\n");
      out.write("                        <div class=\"chooseus__item__icon\">\r\n");
      out.write("                            <img src=\"./resources/img/chooseus/choose-1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chooseus__item__text\">\r\n");
      out.write("                            <h2 class=\"choose-counter\">2146</h2>\r\n");
      out.write("                            <p>Students</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chooseus__item\">\r\n");
      out.write("                        <div class=\"chooseus__item__icon\">\r\n");
      out.write("                            <img src=\"./resources/img/chooseus/choose-2.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chooseus__item__text\">\r\n");
      out.write("                            <h2 class=\"choose-counter\">15</h2>\r\n");
      out.write("                            <p>Years Of Experience</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chooseus__item\">\r\n");
      out.write("                        <div class=\"chooseus__item__icon\">\r\n");
      out.write("                            <img src=\"./resources/img/chooseus/choose-3.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chooseus__item__text\">\r\n");
      out.write("                            <h2 class=\"choose-counter\">48</h2>\r\n");
      out.write("                            <p>Branches</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"chooseus__item\">\r\n");
      out.write("                        <div class=\"chooseus__item__icon\">\r\n");
      out.write("                            <img src=\"./resources/img/chooseus/choose-4.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chooseus__item__text\">\r\n");
      out.write("                            <h2 class=\"choose-counter\">234</h2>\r\n");
      out.write("                            <p>Expert Staffs</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6\">\r\n");
      out.write("                    <div class=\"chooseus__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/chooseus/choose-pic.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Chooseus Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Classes Section Begin -->\r\n");
      out.write("    <section class=\"upcoming-classes spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title normal-title\">\r\n");
      out.write("                        <h2>Upcoming Courses</h2>\r\n");
      out.write("                        <p>The trainings are multi-style and you will learn and practice Hatha Vinyasa (flow)<br /> and\r\n");
      out.write("                            Yin Yoga.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"classes__item\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                            <span>20 Jun 2019</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <p>14 Days | Start on 10th Every Month</p>\r\n");
      out.write("                            <h4><a href=\"#\">100 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"classes__item\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-2.jpg\">\r\n");
      out.write("                            <span>20 Jun 2019</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <p>14 Days | Start on 10th Every Month</p>\r\n");
      out.write("                            <h4><a href=\"#\">200 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"classes__item\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-3.jpg\">\r\n");
      out.write("                            <span>20 Jun 2019</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <p>14 Days | Start on 10th Every Month</p>\r\n");
      out.write("                            <h4><a href=\"#\">300 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Classes Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Gallery Section Begin -->\r\n");
      out.write("    <section class=\"gallery\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title normal-title\">\r\n");
      out.write("                        <h2>Our Gallery</h2>\r\n");
      out.write("                        <p>This is the beautiful yogi and yoginis that have shared their journey and growth with<br />\r\n");
      out.write("                            us. Take a look!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-4.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-5.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-6.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-7.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 p-0\">\r\n");
      out.write("                    <div class=\"gallery__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/gallery/gallery-8.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Gallery Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Team Section Begin -->\r\n");
      out.write("    <section class=\"instructor spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title normal-title\">\r\n");
      out.write("                        <h2>Meet Our Instructors</h2>\r\n");
      out.write("                        <p>Our Indian and western teachers are highly qualified and will be happy to share this<br />\r\n");
      out.write("                            spiritual journey with you.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"instructor__item\">\r\n");
      out.write("                        <div class=\"instructor__item__pic\">\r\n");
      out.write("                            <img src=\"./resources/img/instructor/instructor-1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"instructor__item__text\">\r\n");
      out.write("                            <h5>Emma Hale</h5>\r\n");
      out.write("                            <span>Yoga Trainer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"instructor__item\">\r\n");
      out.write("                        <div class=\"instructor__item__pic\">\r\n");
      out.write("                            <img src=\"./resources/img/instructor/instructor-2.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"instructor__item__text\">\r\n");
      out.write("                            <h5>Rebecca James</h5>\r\n");
      out.write("                            <span>Yoga Trainer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"instructor__item\">\r\n");
      out.write("                        <div class=\"instructor__item__pic\">\r\n");
      out.write("                            <img src=\"./resources/img/instructor/instructor-3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"instructor__item__text\">\r\n");
      out.write("                            <h5>Melissa Smith</h5>\r\n");
      out.write("                            <span>Yoga Trainer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"instructor__item\">\r\n");
      out.write("                        <div class=\"instructor__item__pic\">\r\n");
      out.write("                            <img src=\"./resources/img/instructor/instructor-4.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"instructor__item__text\">\r\n");
      out.write("                            <h5>Emily Walker</h5>\r\n");
      out.write("                            <span>Yoga Trainer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Team Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Appoinment Section Begin -->\r\n");
      out.write("    <section class=\"appointment\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"appointment__text\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"section-title\">\r\n");
      out.write("                            <img src=\"./resources/img/icon-white.png\" alt=\"\">\r\n");
      out.write("                            <h2>Make An Appointment</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"#\" class=\"appointment__form\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Phone\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <select class=\"class-select\">\r\n");
      out.write("                                <option value=\"\">Choose Your Class</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                            <textarea placeholder=\"Message\"></textarea>\r\n");
      out.write("                            <button type=\"submit\">Submit</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Appoinment Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonial Section Begin -->\r\n");
      out.write("    <section class=\"testimonial spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"testimonial__slider owl-carousel\">\r\n");
      out.write("                <div class=\"testimonial__item\">\r\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"col-lg-10\">\r\n");
      out.write("                            <div class=\"testimonial__text\">\r\n");
      out.write("                                <p>This is my second time completing a 200 hr TTC from Zogin and I loved the experiences\r\n");
      out.write("                                    even more than the first time that I had done in 2014.</p>\r\n");
      out.write("                                <img src=\"./resources/img/testimonial/testimonial-1.png\" alt=\"\">\r\n");
      out.write("                                <h5>Linnie Walton <span>- Trainer</span></h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial__item\">\r\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"col-lg-10\">\r\n");
      out.write("                            <div class=\"testimonial__text\">\r\n");
      out.write("                                <p>This is my second time completing a 200 hr TTC from Zogin and I loved the experiences\r\n");
      out.write("                                    even more than the first time that I had done in 2015.</p>\r\n");
      out.write("                                <img src=\"./resources/img/testimonial/testimonial-1.png\" alt=\"\">\r\n");
      out.write("                                <h5>Linnie Walton <span>- Trainer</span></h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial__item\">\r\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"col-lg-10\">\r\n");
      out.write("                            <div class=\"testimonial__text\">\r\n");
      out.write("                                <p>This is my second time completing a 200 hr TTC from Zogin and I loved the experiences\r\n");
      out.write("                                    even more than the first time that I had done in 2016.</p>\r\n");
      out.write("                                <img src=\"./resources/img/testimonial/testimonial-1.png\" alt=\"\">\r\n");
      out.write("                                <h5>Linnie Walton <span>- Trainer</span></h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"testimonial__item\">\r\n");
      out.write("                    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("                        <div class=\"col-lg-10\">\r\n");
      out.write("                            <div class=\"testimonial__text\">\r\n");
      out.write("                                <p>This is my second time completing a 200 hr TTC from Zogin and I loved the experiences\r\n");
      out.write("                                    even more than the first time that I had done in 2017.</p>\r\n");
      out.write("                                <img src=\"./resources/img/testimonial/testimonial-1.png\" alt=\"\">\r\n");
      out.write("                                <h5>Linnie Walton <span>- Trainer</span></h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Testimonial Section End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"./resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
