/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-18 00:48:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trainerApply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Breadcrumb Begin -->\r\n");
      out.write("    <section class=\"breadcrumb-option set-bg\" data-setbg=\"./resources/img/breadcrumb.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb__text\">\r\n");
      out.write("                        <h2>마이페이지</h2>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Breadcrumb End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Blog Section Begin -->\r\n");
      out.write("    <section class=\"blog spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 order-lg-1 order-2\">\r\n");
      out.write("                    <div class=\"blog__sidebar\">\r\n");
      out.write("                        <div class=\"blog__sidebar__categories\">\r\n");
      out.write("                            <h4>카테고리</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"myinfo\">내정보</a></li>\r\n");
      out.write("                                <li><a href=\"bookmark\">북마크</a></li>\r\n");
      out.write("                                <li><a href=\"trainerApply\">트레이너신청(전)</a></li>\r\n");
      out.write("                                <li><a href=\"trainerInfo\">트레이너정보(후)</a></li>\r\n");
      out.write("                                <li><a href=\"listenList\">마이클래스(일반)</a></li>\r\n");
      out.write("                                <li><a href=\"teachList\">마이클래스(트레이너)</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__sidebar__recent\">\r\n");
      out.write("                            <h4>최신글</h4>\r\n");
      out.write("                            <div class=\"blog__recent__item\">\r\n");
      out.write("                                <div class=\"blog__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/blog/br-1.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__recent__item__text\">\r\n");
      out.write("                                    <h6>09 Kinds Of Vegetables Protect The Liver</h6>\r\n");
      out.write("                                    <span>MAR 05, 2019</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog__recent__item\">\r\n");
      out.write("                                <div class=\"blog__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/blog/br-2.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__recent__item__text\">\r\n");
      out.write("                                    <h6>Tips You To Balance Nutrition Meal Day</h6>\r\n");
      out.write("                                    <span>MAR 05, 2019</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog__recent__item\">\r\n");
      out.write("                                <div class=\"blog__recent__item__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/blog/br-3.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"blog__recent__item__text\">\r\n");
      out.write("                                    <h6>4 Principles Help You Lose Weight With Vegetables</h6>\r\n");
      out.write("                                    <span>MAR 05, 2019</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__sidebar__tags\">\r\n");
      out.write("                            <h4>인기 검색어</h4>\r\n");
      out.write("                            <a href=\"#\">Weight</a>\r\n");
      out.write("                            <a href=\"#\">Beauty</a>\r\n");
      out.write("                            <a href=\"#\">Yoga Ball</a>\r\n");
      out.write("                            <a href=\"#\">Fruit</a>\r\n");
      out.write("                            <a href=\"#\">Healthy Food</a>\r\n");
      out.write("                            <a href=\"#\">Lifestyle</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 여기부터 달라짐 -->\r\n");
      out.write("                <div class=\"col-lg-8 order-lg-2 order-1\">\r\n");
      out.write("                    <div class=\"row\" style=\"display: inline-block;width: 100%;\" >\r\n");
      out.write("                        \t<!-- Appoinment Section Begin -->\r\n");
      out.write("\t<section class=\"appointment\" style=\" margin-bottom: 50px;\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"appointment__text\" style=\"background-color: #9e9e9e0a\">\r\n");
      out.write("\t\t\t\t<!-- <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2></h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<form action=\"#\" class=\"appointment__form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t<h4 style=\"font-family: DM Sans, sans-serif;color: #111111;font-weight: 400;\">트레이너 신청</h4>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"font-family: DM Sans, sans-serif;font-size: 1.2em;color:#5768AD;\">본인의 정보를 정확히 입력하여 신청해주세요. </p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"color:#5768AD;\">▶ 보완처리시 휴대폰번호로 연락드립니다.</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"color:#5768AD;\">▶ 첨부서류는 <span style=\"color:#FC7F65;\">pdf</span> 파일로 첨부해주세요.</p>\r\n");
      out.write("\t\t\t\t\t\t<p style=\"color:#5768AD;\">▶ 경력과 수상이력은 해당양식에 맞춰 작성해주세요.</p>\r\n");
      out.write("\t\t\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">이름</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #3f51b50d; color: black;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"마동석\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">성별</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"r_gender\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"gend_type\" id=\"male\" value=\"남자\" autocomplete=\"off\" style=\"opacity: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"male\" style=\"border:1px solid;float:left;\">남자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"gend_type\" id=\"female\" value=\"여자\" autocomplete=\"off\" style=\"opacity: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"female\" style=\"border:1px solid;\" >여자</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">핸드폰번호</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Mobile\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #3f51b50d; color: black;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">소속헬스장</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"GYM Name\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #3f51b50d; color: black;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">수상이력</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #3f51b50d; color: black; margin-bottom: 20px;resize: none;\">\r\n");
      out.write("2014~2019 서울 멋진헬스장 트레이너 \r\n");
      out.write("2020~현재 대전 멋쟁이헬스장 트레이너 & 요가강사\r\n");
      out.write("2014~2019 서울 멋진헬스장 트레이너 \r\n");
      out.write("2020~현재 대전 멋쟁이헬스장 트레이너 & 요가강사\r\n");
      out.write("2014~2019 서울 멋진헬스장 트레이너 \r\n");
      out.write("\r\n");
      out.write("                                    </textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">경력</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #3f51b50d; color: black; margin-bottom: 20px;resize: none;\">\r\n");
      out.write("2014~2019 서울 멋진헬스장 트레이너 \r\n");
      out.write("2020~현재 대전 멋쟁이헬스장 트레이너 & 요가강사\r\n");
      out.write("2014~2019 서울 멋진헬스장 트레이너 \r\n");
      out.write("2020~현재 대전 멋쟁이헬스장 트레이너 & 요가강사\r\n");
      out.write("2014~2019 서울 멋진헬스장 트레이너 \r\n");
      out.write("\r\n");
      out.write("                                    </textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom: 2px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h5 style=\"display: inline; float: left; color: black;\">첨부파일</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\" style=\"text-align: right; float: left; padding: 0; margin: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"첨부파일 추가\" class=\"site-btn updateBtn\" style=\"float:right; padding: 1px 6px ;font-size: 0.8em; color: white; background-color: #5768AD; width: 130px; height: 40px; margin-right: 7px;\" onclick=\"fn_update()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"file\" style=\"background-color: #3f51b50d;color: black; margin-bottom: 5px;\" value=\"성범죄자 이력 조회 서류\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"input-group\" style=\"margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"file\" style=\"background-color: #3f51b50d;color: black; margin-bottom: 5px;\" value=\"성범죄자 이력 조회 서류\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t\t        <div class=\"input-group\" style=\"margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"file\" style=\"background-color: #3f51b50d;color: black; margin-bottom: 5px;\" value=\"성범죄자 이력 조회 서류\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\" style=\"margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"file\" style=\"background-color: #3f51b50d;color: black; margin-bottom: 5px;\" value=\"성범죄자 이력 조회 서류\">\r\n");
      out.write("\t\t\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\" style=\"text-align: right;\">\r\n");
      out.write("\t\t\t                             <button type=\"submit\" class=\"site-btn\" style=\"font-size: 1.1em;color: white; background-color: #5768AD;width: 150px;height: 48px;margin-right: 7px;\">신청</button>\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- Appoinment Section End -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Section End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"./resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
