/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-18 02:50:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.diet;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chatDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction fn_numberAlert(){\r\n");
      out.write("\t\t if(confirm(\"상담을 진행하면 이용권 하나가 차감됩니다. 계속 진행하시겠습니까?\"))\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t  \tlocation.href=\"chatting\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Breadcrumb Begin -->\r\n");
      out.write("    <section class=\"breadcrumb-option set-bg\" data-setbg=\"./resources/img/breadcrumb.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb__text\">\r\n");
      out.write("                        <h2>1:1 상담</h2>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("<!-- Breadcrumb End -->\r\n");
      out.write("<section class=\"about spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"about__services\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-7 p-0\">\r\n");
      out.write("                    <div class=\"about__pic\">\r\n");
      out.write("                        <img src=\"./resources/img/common/trainer-1.jpg\" style=\"width: 500px;height: 500px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-5 p-0\">\r\n");
      out.write("                    <div class=\"about__text\">\r\n");
      out.write("                        <div class=\"section-title\">\r\n");
      out.write("                            <h2>곽두팔 <span style=\"font-size: 0.6em;color:#5768AD\">헬스 트레이너</span></h2>\r\n");
      out.write("                            <p>땡땡 소속 전문 헬스트레이너 곽두팔 입니다. 식단이 중요한 만큼 고객에 맞는 상담을 해드립니다. 연락...주십쇼..</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"appointment__text\" style=\"background-color: #9e9e9e0a;padding:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2></h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" class=\"appointment__form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6 text-center mypage_myinfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"margin-right: auto; max-width: 100%; width: 500px; margin-left: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12 text-center\" style=\"padding:0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"background-color: #3f51b50d; color: black;padding:20px;margin:0;border-radius: 10px;resize: none;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twidth: 460px;height: 300px;\">\r\n");
      out.write("*공지사항*\r\n");
      out.write("- 예약을 원하시면 댓글을 달아주세요 합의 후 진행예정.\r\n");
      out.write("- 2021/06/18 상담 없는 날입니다.\r\n");
      out.write("\r\n");
      out.write("*2021/06/17 예약현황*\r\n");
      out.write("15:00 ~ 15:20 김도민님 예약완료\r\n");
      out.write("15:30 ~ 15:50 옹나희님 예약완료\r\n");
      out.write("16:00 ~ 16:20 반석호님 예약완료\r\n");
      out.write("16:30 ~ 16:50 홍은기님 예약완료</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"classes__item__text\"  style=\"text-align: center;padding-top: 10px;\">\r\n");
      out.write("\t\t\t         <a class=\"class-btn_w\" style=\"font-size: 1.1em;\" onclick=\"fn_numberAlert()\">1:1 상담하기</a>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- About Section End -->\r\n");
      out.write("\t<!-- Leave Comment Begin -->\r\n");
      out.write("    <div class=\"leave-comment spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"leave__comment__text\">\r\n");
      out.write("                        <h2>트레이너에게 문의해보세요👀</h2>\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-12\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                                    <textarea placeholder=\"댓글을 입력해 주세요.\"></textarea>\r\n");
      out.write("                                    <button type=\"submit\" class=\"site-btn\" style=\"font-size: 1.2em;\">작성 완료</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-4 order-lg-1 order-2\" style=\"width: 100%;flex: 0 0 100%;max-width: 100%;padding-right: 0px;margin-left: 23px;\">\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"blog__sidebar\">\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"blog__sidebar__comment\" style=\"overflow:scroll; height: 500px;overflow-x:hidden\">\r\n");
      out.write("                            <h4>댓글</h4>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-1.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Brandon Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,\r\n");
      out.write("                                        adipisci velit,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classes__sidebar__comment\">\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__pic\">\r\n");
      out.write("                                    <img src=\"./resources/img/classes-details/comment-2.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"classes__sidebar__comment__rating\">\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa fa-star-half-o\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"classes__sidebar__comment__text\">\r\n");
      out.write("                                    <span>04 Mar 2018</span>\r\n");
      out.write("                                    <h6>Christina Kelley</h6>\r\n");
      out.write("                                    <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Leave Comment End -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- Js Plugins -->\r\n");
      out.write("    <script src=\"./resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
