/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-15 10:18:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class classes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Breadcrumb Begin -->\r\n");
      out.write("    <section class=\"breadcrumb-option set-bg\" data-setbg=\"./resources/img/breadcrumb.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"breadcrumb__text\">\r\n");
      out.write("                        <h2>Our Classes</h2>\r\n");
      out.write("                        <div class=\"breadcrumb__widget\">\r\n");
      out.write("                            <a href=\"./index.html\">Home</a>\r\n");
      out.write("                            <span>Our Classes</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Breadcrumb End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Classes Section Begin -->\r\n");
      out.write("    <section class=\"classes spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"classes__filter\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"class__filter__select\">\r\n");
      out.write("                                <p>Filter By Day:</p>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>All</option>\r\n");
      out.write("                                    <option>Option 1</option>\r\n");
      out.write("                                    <option>Option 2</option>\r\n");
      out.write("                                    <option>Option 3</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__select\">\r\n");
      out.write("                                <p>Level:</p>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>All Levels</option>\r\n");
      out.write("                                    <option>Option 1</option>\r\n");
      out.write("                                    <option>Option 2</option>\r\n");
      out.write("                                    <option>Option 3</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__select\">\r\n");
      out.write("                                <p>Teacher:</p>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>All Teachers</option>\r\n");
      out.write("                                    <option>Option 1</option>\r\n");
      out.write("                                    <option>Option 2</option>\r\n");
      out.write("                                    <option>Option 3</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__select\">\r\n");
      out.write("                                <p>Style:</p>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option>All Styles</option>\r\n");
      out.write("                                    <option>Option 1</option>\r\n");
      out.write("                                    <option>Option 2</option>\r\n");
      out.write("                                    <option>Option 3</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"class__filter__btn\">\r\n");
      out.write("                                <button><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-1.jpg\">\r\n");
      out.write("                            <span>Beginer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">100 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-2.jpg\">\r\n");
      out.write("                            <span>All levels</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">200 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-3.jpg\">\r\n");
      out.write("                            <span>Beginer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">300 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-4.jpg\">\r\n");
      out.write("                            <span>Beginer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">100 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-5.jpg\">\r\n");
      out.write("                            <span>All levels</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">200 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-6.jpg\">\r\n");
      out.write("                            <span>Beginer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">300 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-7.jpg\">\r\n");
      out.write("                            <span>Beginer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">100 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-8.jpg\">\r\n");
      out.write("                            <span>All levels</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">200 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item classes__item__page\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-9.jpg\">\r\n");
      out.write("                            <span>Beginer</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><span class=\"icon_calendar\"></span> Mon, Wed, Fri</li>\r\n");
      out.write("                                <li><span class=\"icon_clock_alt\"></span> 18:30 - 19:30</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h4><a href=\"#\">300 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"classes__pagination\">\r\n");
      out.write("                        <a href=\"#\">1</a>\r\n");
      out.write("                        <a href=\"#\">2</a>\r\n");
      out.write("                        <a href=\"#\"><span class=\"arrow_carrot-right\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Classes Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Upcoming Classes Section Begin -->\r\n");
      out.write("    <section class=\"upcoming-classes top-classes spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title normal-title\">\r\n");
      out.write("                        <h2>Top Classes</h2>\r\n");
      out.write("                        <p>The trainings are multi-style and you will learn and practice Hatha Vinyasa (flow)<br /> and\r\n");
      out.write("                            Yin Yoga.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-10.jpg\">\r\n");
      out.write("                            <span>20 Jun 2019</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <p>14 Days | Start on 10th Every Month</p>\r\n");
      out.write("                            <h4><a href=\"#\">100 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-11.jpg\">\r\n");
      out.write("                            <span>20 Jun 2019</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <p>14 Days | Start on 10th Every Month</p>\r\n");
      out.write("                            <h4><a href=\"#\">200 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"classes__item\">\r\n");
      out.write("                        <div class=\"classes__item__pic set-bg\" data-setbg=\"./resources/img/classes/classes-12.jpg\">\r\n");
      out.write("                            <span>20 Jun 2019</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"classes__item__text\">\r\n");
      out.write("                            <p>14 Days | Start on 10th Every Month</p>\r\n");
      out.write("                            <h4><a href=\"#\">300 Hour Yoga Course Rishikesh</a></h4>\r\n");
      out.write("                            <h6>Jordan Lawson <span>- Yoga Teacher</span></h6>\r\n");
      out.write("                            <a href=\"#\" class=\"class-btn\">JOIN NOW</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Upcoming Classes Section End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"./resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.barfiller.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"./resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
