/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2021-06-17 10:57:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/profit/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1621901952890L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/7.LastProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/profit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--     Page Preloder\r\n");
      out.write("    <div id=\"preloder\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Offcanvas Menu Begin -->\r\n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\r\n");
      out.write("    <div class=\"offcanvas-menu\">\r\n");
      out.write("        <div class=\"offcanvas__logo\">\r\n");
      out.write("            <a href=\"home\"><img src=\"./resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("        <div class=\"offcanvas__widget dropdown\">\r\n");
      out.write("\t\t\t<p><a style=\"color:gray\">송하나님</a></p>                \r\n");
      out.write("\t\t\t<p><a style=\"color:gray\" href=\"myinfo\">마이페이지</a></p>                \r\n");
      out.write("\t\t\t<p><a style=\"color:gray\">로그아웃</a></p>                \r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"header__menu\">\r\n");
      out.write("            <ul class=\"mobile-menu\">\r\n");
      out.write("                <li class=\"active\"><a href=\"home\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"aiTeachList\">AI교정</a></li>                \r\n");
      out.write("                <li><a href=\"#\">식단관리</a>\r\n");
      out.write("                    <ul class=\"dropdown\">\r\n");
      out.write("                        <li><a href=\"chatList\">1:1 상담</a></li>\r\n");
      out.write("                        <li><a href=\"\">칼로리 계산기</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li> \r\n");
      out.write("                <li><a href=\"lessionList\">온라인클래스</a></li>\r\n");
      out.write("                <li><a href=\"#\">커뮤니티</a>\r\n");
      out.write("                    <ul class=\"dropdown\">\r\n");
      out.write("                        <li><a href=\"recipeList\">레시피</a></li>\r\n");
      out.write("                        <li><a href=\"boardList\">자유게시판</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li> \r\n");
      out.write("                <li><a href=\"noticeList\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"qnaList\">문의하기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"offcanvas__social\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Offcanvas Menu End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Section Begin -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"header__top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("<!--                     <div class=\"col-lg-3 col-md-3\"> -->\r\n");
      out.write("<!--                         <div class=\"header__logo\"> -->\r\n");
      out.write("<!--                             <a href=\"home\"><img src=\"./resources/img/logo.png\" alt=\"\"></a> -->\r\n");
      out.write("<!--                         </div> -->\r\n");
      out.write("<!--                     </div> -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"canvas__open\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("<!--             id=\"header_info\"  -->\r\n");
      out.write("            <div style=\"width: 100%; \">\r\n");
      out.write("            \t\t<div class=\"header__logo header_info\" style=\"display: inline-block;padding-left: 15%;\">\r\n");
      out.write("                            <a href=\"home\"><img src=\"./resources/img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"header_info\" style=\"vertical-align: bottom;text-align: right;float: right;height: 100%;padding-top: 70px;padding-right: 50px;\">\r\n");
      out.write("                    <a href=\"trainerPermitList\" style=\"color: gray;font-size: 0.9em;padding-left: 10px;\">관리자님</a>\r\n");
      out.write("                    <a href=\"myinfo\" style=\"color: gray;font-size: 0.9em;padding-left: 10px;\">마이페이지</a>\r\n");
      out.write("                    <a href=\"login\" style=\"color: gray;font-size: 0.9em;padding-left: 10px;\">로그인</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("      \t    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"header__nav\">\r\n");
      out.write("            <div class=\"container\" style=\"text-align: center;\">\r\n");
      out.write("                <div class=\"row\" style=\"flex-wrap: nowrap;display: inline-block;\">\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"col-lg-9 col-md-9\" style=\"max-width: 100%;margin: 0;\">\r\n");
      out.write("                        <nav class=\"header__menu\" >\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li class=\"active\"><a href=\"home\">Home</a></li>\r\n");
      out.write("                                <li><a href=\"aiTeachList\">AI교정</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">식단관리</a>\r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                        <li><a href=\"chatList\">1:1 상담</a></li>\r\n");
      out.write("                                        <li><a href=\"\">칼로리 계산기</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"lessionList\">온라인클래스</a></li>\r\n");
      out.write("                                <li><a href=\"#\">커뮤니티</a>\r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                        <li><a href=\"recipeList\">레시피</a></li>\r\n");
      out.write("                                        <li><a href=\"boardList\">자유게시판</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"noticeList\">공지사항</a></li>\r\n");
      out.write("                                <li><a href=\"qnaList\">문의하기</a></li>\r\n");
      out.write("<!--                                 <li><a href=\"#\">예시</a> -->\r\n");
      out.write("<!--                                     <ul class=\"dropdown\"> -->\r\n");
      out.write("<!--                                         <li><a href=\"aboutUs\">aboutUs</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"blog\">blog</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"blogDetail\">blogDetails</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"classes\">classes</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"classesDetail\">classesDetails</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"contact\">contact</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"faq\">faq</a></li> -->\r\n");
      out.write("<!--                                         <li><a href=\"pricing\">pricing</a></li> -->\r\n");
      out.write("<!--                                     </ul> -->\r\n");
      out.write("<!--                                 </li> -->\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Section End -->\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
